name:                haskell-math-expressions-eval
version:             0.1.0.0
github:              "aammfe/haskell-math-expressions-eval"
license:             BSD3
author:              "Abdul"
maintainer:          "aammfe@gmail.com"
copyright:           "2021 Abdul Hanan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-math-expressions-eval#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-math-expressions-eval-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-math-expressions-eval

tests:
  haskell-math-expressions-eval-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-math-expressions-eval
